create table if not exists public.tasks (
  task_id bigint generated by default as identity primary key,
  owner_id uuid not null default auth.uid()
    references auth.users(id) on delete cascade,
  title text not null,
  assigned_member text not null,
  status text not null default 'Not Done',
  deadline date not null
);

create table if not exists public.task_updates (
  update_id bigint generated by default as identity primary key,
  task_id bigint not null
    references public.tasks(task_id) on delete cascade,
  owner_id uuid not null default auth.uid()
    references auth.users(id) on delete cascade,
  update_text text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.bug_reports (
  bug_id bigint generated by default as identity primary key,
  owner_id uuid not null default auth.uid()
    references auth.users(id) on delete cascade,
  user_story text not null,
  summary text not null,
  priority text not null,
  status text not null default 'Todo'
);

alter table public.tasks enable row level security;

alter table public.task_updates
enable row level security;

alter table public.bug_reports
enable row level security;

create policy "tasks select own"
on public.tasks
for select
to authenticated
using (auth.uid() = owner_id);

create policy "tasks insert own"
on public.tasks
for insert
to authenticated
with check (auth.uid() = owner_id);

create policy "tasks update own"
on public.tasks
for update
to authenticated
using (auth.uid() = owner_id);

create policy "tasks delete own"
on public.tasks
for delete
to authenticated
using (auth.uid() = owner_id);

create policy "updates select own"
on public.task_updates
for select
to authenticated
using (auth.uid() = owner_id);

create policy "updates insert own"
on public.task_updates
for insert
to authenticated
with check (auth.uid() = owner_id);

create policy "bugs select own"
on public.bug_reports
for select
to authenticated
using (auth.uid() = owner_id);

create policy "bugs insert own"
on public.bug_reports
for insert
to authenticated
with check (auth.uid() = owner_id);

create policy "bugs update own"
on public.bug_reports
for update
to authenticated
using (auth.uid() = owner_id);

grant select, insert, update, delete
on public.tasks
to authenticated;

grant select, insert, update, delete
on public.task_updates
to authenticated;

grant select, insert, update, delete
on public.bug_reports
to authenticated;

grant usage, select
on all sequences in schema public
to authenticated;